### ISSUE TITLE
Error messages not appearing

### ISSUE THREAD

**Issue by Automage** [nalinahuja22/cstring#1]
Excellent work Balin!

Tried testing out the error messages for cstring with this program:
```
  1 #include "cstring.h"
  2 #include <stdio.h>
  3 int main() {
  4   string *test = cstring("hello");
  5   insert(test, NULL, 0);
  6   printf("%s\n", test->str);
  7 }
```

But it doesn't display any error messages (i.e. in _verify), just segfaults. Is this intended?

Also, thoughts on renaming insert, copy, etc. to something more specific to avoid naming conflicts in user code?

**Comment by nalinahuja** [comment]
YOO, thanks for the bug report. Was a missing part of the assertion statement in the insert function. Probably more in this that I haven't caught yet, need to review and refactor this entire thing one day. As for your latter concern, its very dependent on the situation. I could rename them to cstring_add but then that would become tedious. However, I think that if I use long, unique function names and have a bunch of wrapper functions which you can include from a separate file, that would be the best solution that I can think of right now given that C is not object oriented.
